#!/bin/bash


fuc_utilidades () {

#UTILIDADES
cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}"  \
--no-tags --ok-label "${btn_confirm}" --cancel-label "${cancel_label}" --checklist "${text_menu_chklist}" 22 80 22)
options=(1 "${msg_extras_op1}" on    # any option can be set to default to "on"
         2 "${msg_extras_op2}" on
         3 "${msg_extras_op3}" off
         4 "${msg_extras_op4}" off
         5 "${msg_extras_op5}" off
         6 "${msg_extras_op6}" off
         7 "${msg_extras_op7}" off
         8 "${msg_extras_op8}" off
         9 "${msg_extras_op9}" off
         10 "${msg_extras_op10}" off
         11 "${msg_extras_op11}" off
         12 "${msg_extras_op12}" off
         13 "${msg_extras_op13}" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
1)
UTIL1=true
;;

2)
UTIL2=true
;;

3)
UTIL3=true
;;

4)
UTIL4=true
;;

5)
UTIL5=true
;;

6)
UTIL6=true
;;

7)
UTIL7=true
;;

8) 
UTIL8=true
;;

9)
UTIL9=true
;;   

10)
UTIL10=true
;;


11)
UTIL11=true
;; 

12)
UTIL12=true
;; 

13)
UTIL13=true
;; 

    esac
done
#FINAL DE UTILIDADES

}


fuc_terminales () {

#TERMINALES
cmd=(dialog --no-collapse --cr-wrap --title "${msg_extras_term}" --backtitle "${title}"  \
--no-tags --ok-label "${btn_confirm}" --cancel-label "${cancel_label}" --checklist "${text_menu_checklist}" 17 80 17)
options=(1 "${msg_extras_term1}" on    # any option can be set to default to "on"
         2 "${msg_extras_term2}" off
         3 "${msg_extras_term3}" off
         4 "${msg_extras_term4}" off
         5 "${msg_extras_term5}" off
         6 "${msg_extras_term6}" off
         7 "${msg_extras_term7}" off
         8 "${msg_extras_term8}" off
         9 "${msg_extras_term9}" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            TERMI1=true
            ;;
        2)
            TERMI2=true
            ;;
        3)
            TERMI3=true
            ;;
        4)
            TERMI4=true
            ;;
        
        5)
            TERMI5=true
            ;;

        6)
            TERMI6=true
            ;;
               
        7)
            TERMI7=true
            ;;   
        8)
            TERMI8=true
            ;;   
        9)
            TERMI9=true
            ;;   
    esac
done
#FINAL DE TERMINALES
}


fuc_audiosistema () {

#AUDIO
cmd=(dialog --no-collapse --cr-wrap --title "${msg_extras_audio}" --backtitle "${title}"  \
--no-tags --ok-label "${btn_confirm}" --cancel-label "${cancel_label}" --radiolist "${text_menu_audio}" 17 80 17)
options=(1 "${msg_extras_audio1}" on    # any option can be set to default to "on"
         2 "${msg_extras_audio2}" off    
         3 "${msg_extras_audio3}" off
         4 "${msg_extras_audio4}" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in

        1)
            AUDIO1=true
            # https://wiki.archlinux.org/title/PipeWire
            ;;

        2)
            AUDIO2=true
            # https://wiki.archlinux.org/index.php/PulseAudio
            # pulseeffects libcanberra-pulse libcanberra-gstreamer 
            ;;

        3)
            AUDIO3=true
            #https://wiki.archlinux.org/index.php/Professional_audio
            ;;

        4)
            AUDIO4=true
            #https://wiki.archlinux.org/index.php/Advanced_Linux_Sound_Architecture
            ;;

    esac
done
#FIN_AUDIO

}



fuc_reproductores () {

#REPRODUCTOR

cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --separate-output --column-separator "|" \
--no-tags --ok-label "${btn_confirm}" --cancel-label "${cancel_label}" \
--title "${msg_extras_player}" \
--checklist ""${text_menu_player}"" 15 80 15)
options=(   1 "${msg_extras_player1}" on
            2 "${msg_extras_player2}" off
            3 "${msg_extras_player3}" off            
            4 "${msg_extras_player4}" off
            5 "${msg_extras_player5}" off
            6 "${msg_extras_player6}" off
            7 "${msg_extras_player7}" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            REPRO1=true
            ;;
        2)
            REPRO2=true
            ;;
        3)
            REPRO3=true
            ;;
        4)
            REPRO4=true
            ;;
        5)
            REPRO5=true
            ;;
        6)
            REPRO6=true
            ;;
        7)
            REPRO7=true
            ;;
    esac
done

# FIN REPRODUCTOR

}



fuc_navegador_web () {

#NAVEGADORES
cmd=(dialog --no-collapse --cr-wrap --title "${msg_extras_browser}" --backtitle "${title}" --separate-output --column-separator "|" \
--no-tags --ok-label "${btn_confirm}" --cancel-label "${cancel_label}" --checklist "${text_menu_browser}" 16 80 16)
options=(1 "${msg_extras_browser1}" on    # any option can be set to default to "on"
         2 "${msg_extras_browser2}" off
         3 "${msg_extras_browser3}" off
         4 "${msg_extras_browser4}" off
         5 "${msg_extras_browser5}" off         
         6 "${msg_extras_browser6}" off
         7 "${msg_extras_browser7}" off
         8 "${msg_extras_browser8}" off)
choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            WEB1=true
            ;;
        2)
            WEB2=true
            ;;
        3)
            WEB3=true
            ;;
        4)
            WEB4=true
            ;;
        5)
            WEB5=true
            ;;
        6)
            WEB6=true
            ;;
        7)
            WEB7=true
            ;;
        8)
            WEB8=true
            ;; 
    esac
done
# FIN NAVEGADORES

}




fuc_ofimatica () {

#OFFICE
cmd=(dialog --no-collapse --cr-wrap --title "${msg_extras_office}" --backtitle "${title}" --separate-output --column-separator "|" \
--no-tags --ok-label "${btn_confirm}" --cancel-label "${cancel_label}" --checklist "${text_menu_office}" 12 80 12)
options=(    1 "${msg_extras_office1}" on
             2 "${msg_extras_office2}" off
             3 "${msg_extras_office3}" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            OFFICE1=true
            ;;
        2)
            OFFICE2=true
            ;;
        3)
            OFFICE3=true
            ;;
    esac
done
# FIN OFFICE

}



fuc_administrador_de_tareas () {

#Administrador de Tareas
cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --title "${msg_extras_tm}" \
--no-tags  --ok-label "${btn_confirm}" --cancel-label "${cancel_label}" --checklist "${text_menu_tm}" 14 80 14)
options=(1 "${msg_extras_tm1}" on
         2 "${msg_extras_tm2}" on
         3 "${msg_extras_tm3}" off
         4 "${msg_extras_tm4}" off
         5 "${msg_extras_tm5}" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            AP1=true
            ;;
        2)
            AP2=true
            ;;
        3)
            AP3=true
            ;;
        4)
            AP4=true
            ;;
        5)
            AP5=true
            ;;
            
            
    esac
done



}



fuc_social () {

#Redes Sociales
cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}"  --title "${msg_extras_social}" \
--no-tags  --ok-label "${btn_confirm}" --cancel-label "${cancel_label}" --column-separator "|" --checklist "${text_menu_social}" 15 80 20)
options=(1 "${msg_extras_social1}" on
         2 "${msg_extras_social2}" off
         3 "${msg_extras_social3}" off
         4 "${msg_extras_social4}" off
         5 "${msg_extras_social5}" off
         6 "${msg_extras_social6}" off
         7 "${msg_extras_social7}" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            RS1=true
            ;;
        2)
            RS2=true
            ;;
        3)
            RS3=true
            ;;
        4)
            RS4=true
            ;;    
        5)
            RS5=true
            ;;            
        6)
            RS6=true
            ;;

        7)
            RS7=true
            ;;         

    esac
done
#FINAL DE Redes Sociales

}


fuc_gamer () {

#INICIO DE GAMING
cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}"  --title "${msg_extra_game}" \
--no-tags  --ok-label "${btn_confirm}" --cancel-label "${cancel_label}" --column-separator "|" --checklist "${text_menu_game}" 24 80 24)
options=(1 "${msg_extras_game1}" on
         2 "${msg_extras_game2}" off
         3 "${msg_extras_game3}" off
         4 "${msg_extras_game4}" off
         5 "${msg_extras_game5}" off
         6 "${msg_extras_game6}" off
         7 "${msg_extras_game7}" off
         8 "${msg_extras_game8}" off
         9 "${msg_extras_game9}" off
         10 "${msg_extras_game10}" off
         11 "${msg_extras_game11}" off
         12 "${msg_extras_game12}" off
         13 "${msg_extras_game13}" off
         14 "${msg_extras_game14}" off
         15 "${msg_extras_game15}" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            GAM1=true
            ;;
        2)
            GAM2=true
            ;;
        3)
            GAM3=true
            ;;
        4)
            GAM4=true
            ;;    
        5)
            GAM5=true
            ;;            
        6)
            GAM6=true
            ;;
        7)
            GAM7=true
            ;; 
        8)
            GAM8=true
            ;;
        9)
            GAM9=true
            ;; 
        10)
            GAM10=true
            ;; 
        11)
            GAM11=true
            ;;
        12)
            GAM12=true
            ;;
        13)
            GAM13=true
            ;;
        14)
            GAM14=true
            ;;    
        15)
            GAM15=true
            ;; 

    esac
done

#FINAL DE GAMING
}


fuc_aur_helpers () {

cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}"  --title "${msg_extras_aurhelper}" \
--no-tags  --ok-label "${btn_confirm}" --cancel-label "${cancel_label}" --column-separator "|" --checklist "${text_menu_aurhelper}" 19 80 19)
options=(1 "${msg_extras_aurhelper1}" on
         2 "${msg_extras_aurhelper2}" off
         3 "${msg_extras_aurhelper3}" off
         4 "${msg_extras_aurhelper4}" off
         5 "${msg_extras_aurhelper5}" off
         6 "${msg_extras_aurhelper6}" off
         7 "${msg_extras_aurhelper7}" off
         8 "${msg_extras_aurhelper8}" off
         9 "${msg_extras_aurhelper9}" off
         10 "${msg_extras_aurhelper10}" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            AUR1=true
            ;;
        2)
            AUR2=true
            ;;
        3)
            AUR3=true
            ;;
        4)
            AUR4=true
            ;;    
        5)
            AUR5=true
            ;;            
        6)
            AUR6=true
            ;;
        7)
            AUR7=true
            ;; 
        8)
            AUR8=true
            ;;
        9)
            AUR9=true
            ;; 
        10)
            AUR10=true
            ;; 

    esac
done

#FINAL DE AUR

}




extraprogram () {


extraprograms=true

AP_condicion=false
TERMINAL_condicion=false

while [[ $extraprograms == "true" ]]; do

menuextras=$(dialog --keep-tite --backtitle "${title}" --title "${text_menu_extraitems}" \
--ok-label "${btn_confirm}" --default-item "${extras_item}" --no-tags \
--menu "${text_menu_extras}" 20 60 10 \
1 "${msg_extras_section1}" \
2 "${msg_extras_section2}" \
3 "${msg_extras_section3}" \
4 "${msg_extras_section4}" \
5 "${msg_extras_section5}" \
6 "${msg_extras_section6}" \
7 "${msg_extras_section7}" \
8 "${msg_extras_section8}" \
9 "${msg_extras_section9}" \
10 "${msg_extras_section10}" \
11 "${msg_extras_install}" 3>&1 1>&2 2>&3)

case "$menuextras" in

"1")
fuc_utilidades
extras_item="2"
;;

"2") 
fuc_terminales
extras_item="3"
;;

"3")
fuc_audiosistema
extras_item="4"
;;

"4") 
fuc_reproductores
extras_item="5"
;;

"5")
fuc_navegador_web
extras_item="6"
;;

"6")
fuc_ofimatica
extras_item="7"
;;

"7")
fuc_administrador_de_tareas
extras_item="8"
;;

"8")
fuc_social
extras_item="9"
;;

"9")
fuc_gamer
extras_item="10"
;;

"10")
fuc_aur_helpers
extras_item="11"
;;

"11")
extraprograms=false
break
;;

$1)  # BOTON CANCELAR
extraprograms=false
break
;;

    esac
done


}


