#!/bin/bash

deletediskdd () {



################################################################
# SELETC DISK
################################################################

part="$(lsblk -lno NAME,SIZE,TYPE | grep 'disk' | awk '{print "/dev/" $1 " " $2}' | sort -u | sed '/f/d' | sed '/sr/d' )" 
disk=$(dialog --backtitle "${title}" --clear  --ok-label "${msg_part_select}" --no-cancel --menu "${msg_part_select_disk}" 12 50 0 ${part} 2>&1 >/dev/tty)

dialog --backtitle "${title}" --title "${msg_part}" \
--msgbox "${msg_part_delete}" 11 50

dialog --no-collapse --cr-wrap --backtitle "${title}" --title "${msg_part_confirm}" --yesno "${msg_part_delete_confirm}" 12 70
case $? in

   0)
#Desmontamos todo disco y swapoff
swapdisco=$( fdisk -l | grep "/dev/\|swap" | grep swap | awk -F ' ' '{print $1}' )
umount -R /mnt
clear
swapoff ${swapdisco}
clear
swapoff -a
clear
swapon -a
clear
rm /mnt/etc/fstab
clear 


bootarch=$( ls /sys/firmware/efi/ | grep -ic efivars )

case $bootarch in

  1)
dialog --no-collapse --cr-wrap --backtitle "${title}" --title "${msg_fmt_uefi}" --stdout --ok-label "${oklabel}" \
--prgbox "dd if=/dev/zero of="${disk}" bs=4M conv=fsync oflag=direct status=progress  && \
parted ${disk} mklabel gpt && \
fdisk -l ${disk} \
partprobe" 20 80
;;

  0)
dialog --no-collapse --cr-wrap --backtitle "${title}" --title "${msg_fmt_bios}" --stdout --ok-label "${oklabel}" \
--prgbox "dd if=/dev/zero of="${disk}" bs=4M conv=fsync oflag=direct status=progress  && \
parted ${disk} mklabel msdos && \
fdisk -l ${disk} \
partprobe" 20 80
;;

esac

;;

1) 
clear
;;
esac

}